'use client';
import { Suspense, useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertCircle, ArrowLeft, ChevronDown, ChevronRight, Download, Globe2, UserRound } from 'lucide-react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { AppShell } from './app-shell'; import { GlobalFilters } from './global-filters'; import { MetricCard } from './metric-card'; import { AccountSelector } from './account-selector';
import { compact, money } from '@/lib/demo-data'; import { useAnalyticsData } from '@/lib/use-analytics-data';
import { IntegrationAlert, RealDataEmptyState } from './real-data-state';

function AccountViewInner({ routeAccountId }: { routeAccountId: string }) {
  const { data, loading, error } = useAnalyticsData(); const params = useSearchParams(); const router = useRouter();
  const [expanded, setExpanded] = useState<string | null>(null); const [mode, setMode] = useState<'daily' | 'monthly'>('daily');
  const requestedId = params.get('accountId'); const account = data?.accounts.length === 1 ? data.accounts[0] : null;
  useEffect(() => {
    if (!data || requestedId || data.invalidAccount || !data.options.accounts.length) return;
    const candidate = data.options.accounts.find((item) => item.id === routeAccountId) ?? data.options.accounts[0];
    const next = new URLSearchParams(params.toString()); next.set('accountId', candidate.id); router.replace(`/contas/${candidate.id}?${next.toString()}`, { scroll: false });
  }, [data, params, requestedId, routeAccountId, router]);
  const activeExpanded = data?.campaigns.some((campaign) => campaign.id === expanded) ? expanded : data?.campaigns[0]?.id ?? null;
  function exportData() {
    if (!account || !data) return; const csv = `campanha,investimento,impressoes,resultados,custo_por_resultado\n${data.campaigns.map((campaign) => `${campaign.campaign},${campaign.spend},${campaign.impressions},${campaign.results},${campaign.cpr ?? ''}`).join('\n')}`;
    const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${account.id}-campanhas.csv`; anchor.click(); URL.revokeObjectURL(url);
  }
  const back = new URLSearchParams(params.toString()); back.delete('accountId');
  return <AppShell><div className="mx-auto max-w-[1540px] p-4 md:p-6 lg:p-7">
    <Link href={`/?${back.toString()}`} className="mb-4 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-orange-700"><ArrowLeft size={14}/>Voltar ao consolidado</Link>
    <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div className="min-w-0 flex-1">{account ? <><div className="mb-2 flex items-center gap-2"><span className="rounded-md bg-slate-900 px-2 py-1 text-[10px] font-bold text-white">META ADS</span><span className="text-xs text-slate-500">act_{account.metaAccountId}</span></div><h1 className="text-2xl font-bold tracking-[-.035em] text-slate-950 md:text-[28px]">{account.name}</h1><div className="mt-2 flex flex-wrap gap-4 text-xs text-slate-500"><span className="font-semibold text-slate-700">{account.brand}</span><span className="flex items-center gap-1"><Globe2 size={13}/>{account.market}</span><span className="flex items-center gap-1"><UserRound size={13}/>{account.analyst ?? 'Não atribuído'}</span></div></> : <><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.13em] text-orange-700">Performance por conta</p><h1 className="text-2xl font-bold tracking-[-.035em] text-slate-950 md:text-[28px]">Visão por conta</h1><p className="mt-1 text-sm text-slate-500">Selecione uma conta autorizada para consultar os resultados.</p></>}</div><div className="flex w-full flex-col gap-2 sm:w-auto sm:items-end"><AccountSelector accounts={data?.options.accounts ?? []} selectedId={requestedId ?? account?.id} disabled={loading}/><button onClick={exportData} disabled={!account} className="flex h-9 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 shadow-sm disabled:opacity-50"><Download size={15}/>Exportar dados</button></div></div>
    <GlobalFilters accounts={data?.options.accounts} loading={loading} showAccount={false}/>
    {error && <div role="alert" className="mt-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={17}/>{error}</div>}
    {data && <IntegrationAlert integration={data.integration}/>} 
    {data?.invalidAccount && <div role="alert" className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-sm font-bold text-amber-900">Conta inválida ou não autorizada</h2><p className="mt-1 text-xs text-amber-800">Use o seletor acima para escolher uma conta disponível para seu usuário.</p></div>}
    {loading && <div className="mt-4 grid animate-pulse gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,index)=><div key={index} className="h-36 rounded-xl border border-slate-200 bg-white"/>)}</div>}
    {!loading && !data?.invalidAccount && data?.empty && <RealDataEmptyState integration={data.integration}/>} 
    {!loading && account && data && !data.empty && <><section className="metric-grid mt-4 grid gap-3">{data.metrics.map(({key,...metric})=><MetricCard key={key} {...metric}/>)}</section>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_.75fr]"><section className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-bold">Evolução de performance</h2><p className="mt-1 text-xs text-slate-500">Investimento realizado versus meta no período filtrado</p></div><div className="flex rounded-lg bg-slate-100 p-1">{(['daily','monthly'] as const).map((item)=><button key={item} onClick={()=>setMode(item)} className={`rounded-md px-2.5 py-1 text-[10px] font-bold ${mode===item?'bg-white text-slate-900 shadow-sm':'text-slate-500'}`}>{item==='daily'?'Diário':'Mensal'}</button>)}</div></div><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={mode==='daily'?data.daily:data.trends.map((item)=>({day:item.month,realized:item.realized,goal:item.goal}))}><defs><linearGradient id="accountArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f97316" stopOpacity={.2}/><stop offset="100%" stopColor="#f97316" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef0f3"/><XAxis dataKey="day" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip formatter={(value)=>money.format(Number(value))}/><Area dataKey="realized" name="Realizado" type="monotone" stroke="#ea580c" strokeWidth={2.5} fill="url(#accountArea)"/><Area dataKey="goal" name="Meta" type="monotone" stroke="#475569" strokeDasharray="5 4" fill="transparent"/></AreaChart></ResponsiveContainer></div></section><section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-bold">Distribuição por campanha</h2><p className="mt-1 text-xs text-slate-500">Participação no investimento filtrado</p><div className="mt-4 h-[260px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.campaigns} layout="vertical" margin={{left:10,right:12}}><CartesianGrid horizontal={false} stroke="#eef0f3"/><XAxis type="number" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis dataKey="campaign" type="category" width={105} tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={(value)=>money.format(Number(value))}/><Bar dataKey="spend" name="Investimento" fill="#f97316" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></section></div>
      <section className="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-bold">Ranking de campanhas</h2><p className="mt-1 text-xs text-slate-500">Expanda uma campanha para detalhar conjuntos e anúncios</p></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Campanha</th><th className="px-4 py-3">Investimento</th><th className="px-4 py-3">Impressões</th><th className="px-4 py-3">Resultados</th><th className="px-4 py-3">Custo / resultado</th></tr></thead><tbody>{data.campaigns.map((campaign,index)=><tr key={campaign.id} className="border-t border-slate-100"><td className="px-4 py-3"><button onClick={()=>setExpanded(activeExpanded===campaign.id?null:campaign.id)} className="flex items-center gap-2 font-semibold text-slate-800">{activeExpanded===campaign.id?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<span className="text-slate-400">0{index+1}</span>{campaign.campaign}</button>{activeExpanded===campaign.id&&<div className="ml-9 mt-3 rounded-lg border border-orange-100 bg-orange-50/50 p-3 text-[11px] text-slate-600"><strong>Conjunto · Público amplo 25–44</strong><span className="mx-2 text-slate-300">›</span>Anúncio · Variação ativa</div>}</td><td className="px-4 py-3 font-semibold">{money.format(campaign.spend)}</td><td className="px-4 py-3">{compact.format(campaign.impressions)}</td><td className="px-4 py-3">{compact.format(campaign.results)}</td><td className="px-4 py-3">{campaign.cpr===null?'N/A':money.format(campaign.cpr)}</td></tr>)}</tbody></table></div></section>
    </>}
  </div></AppShell>;
}

export function AccountView({ accountId }: { accountId: string }) { return <Suspense fallback={<div className="min-h-screen bg-[#f6f7f9]"/>}><AccountViewInner routeAccountId={accountId}/></Suspense>; }
