'use client';
import { Suspense } from 'react';
import { AlertCircle, AlertTriangle, BadgeDollarSign, CircleGauge, Download, Landmark, TrendingDown, TrendingUp } from 'lucide-react';
import { AppShell } from './app-shell'; import { GlobalFilters } from './global-filters'; import { money } from '@/lib/demo-data'; import { useAnalyticsData } from '@/lib/use-analytics-data';
import type { BalanceRow } from '@/lib/analytics-types';
import { IntegrationAlert, RealDataEmptyState } from './real-data-state';

function tone(status: string) { return status === 'Orçamento excedido' ? 'bg-red-100 text-red-800' : status === 'Risco de estouro' ? 'bg-red-50 text-red-700' : status === 'Abaixo do ritmo' ? 'bg-amber-50 text-amber-700' : status === 'Sem orçamento' ? 'bg-slate-100 text-slate-600' : 'bg-emerald-50 text-emerald-700'; }
function currency(value: number | null) { return value === null ? 'N/A' : money.format(value); }

function BalancesViewInner() {
  const { data, loading, error } = useAnalyticsData(); const rows = data?.balances ?? [];
  const budgetRows = rows.filter((row) => row.budget !== null); const totalBudget = budgetRows.length ? budgetRows.reduce((sum,row)=>sum+(row.budget ?? 0),0) : null;
  const spent = rows.length ? rows.reduce((sum,row)=>sum+row.spent,0) : null; const projectedRows = rows.filter((row)=>row.projection!==null); const projected = projectedRows.length ? projectedRows.reduce((sum,row)=>sum+(row.projection ?? 0),0) : null;
  const risks = rows.filter((row)=>row.status==='Risco de estouro'||row.status==='Orçamento excedido').length; const under = rows.filter((row)=>row.status==='Abaixo do ritmo').length;
  function exportCsv() { const headers='conta,marca,analista,periodo,orcamento,valor_consumido,saldo,percentual_consumido,esperado_ate_data,desvio_ritmo,projecao,diferenca_projetada,dias_restantes,media_diaria_recomendada,status'; const body=rows.map((row)=>[row.name,row.brand,row.analyst,row.periodLabel,row.budget,row.spent,row.balance,row.consumed,row.expected,row.paceDeviation,row.projection,row.projectedDifference,row.remainingDays,row.recommendedDaily,row.status].join(','));const url=URL.createObjectURL(new Blob([`\ufeff${headers}\n${body.join('\n')}`],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='controle-saldos.csv';anchor.click();URL.revokeObjectURL(url); }
  const cards = [{label:'Orçamento total',value:currency(totalBudget),caption:data?`${data.range.start} a ${data.range.end}`:'Período filtrado',icon:Landmark,tone:'text-slate-700 bg-slate-100'},{label:'Valor consumido',value:currency(spent),caption:spent!==null&&totalBudget?`${(spent/totalBudget*100).toFixed(1).replace('.',',')}% do orçamento`:'Sem orçamento cadastrado',icon:BadgeDollarSign,tone:'text-orange-700 bg-orange-50'},{label:'Saldo orçamentário',value:currency(totalBudget===null||spent===null?null:totalBudget-spent),caption:'Saldo interno disponível',icon:CircleGauge,tone:'text-emerald-700 bg-emerald-50'},{label:'Projeção de fechamento',value:currency(projected),caption:totalBudget!==null&&projected!==null?`${money.format(totalBudget-projected)} de diferença`:'N/A',icon:TrendingUp,tone:'text-slate-700 bg-slate-100'},{label:'Subinvestimento',value:String(under),caption:'contas abaixo do ritmo',icon:TrendingDown,tone:'text-amber-700 bg-amber-50'},{label:'Risco de estouro',value:String(risks),caption:'contas exigem atenção',icon:AlertTriangle,tone:'text-red-700 bg-red-50'}];
  return <AppShell><div className="mx-auto max-w-[1680px] p-4 md:p-6 lg:p-7"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.13em] text-orange-700">Financeiro de mídia</p><h1 className="text-2xl font-bold tracking-[-.03em] md:text-[28px]">Controle de saldos</h1><p className="mt-1 text-sm text-slate-500">Ritmo de investimento, projeções e alertas por conta.</p></div><button onClick={exportCsv} disabled={!rows.length} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 shadow-sm disabled:opacity-50"><Download size={15}/>Exportar CSV</button></div><GlobalFilters accounts={data?.options.accounts} loading={loading}/>
    {error&&<div role="alert" className="mt-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={17}/>{error}</div>}
    {data&&<IntegrationAlert integration={data.integration}/>} 
    {loading&&<div className="mt-4 grid animate-pulse gap-3 sm:grid-cols-2 xl:grid-cols-6">{Array.from({length:6},(_,index)=><div key={index} className="h-36 rounded-xl border border-slate-200 bg-white"/>)}</div>}
    {!loading&&data?.empty&&<RealDataEmptyState integration={data.integration}/>} 
    {!loading&&data&&!data.empty&&<><section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards.map((card)=><article key={card.label} className="rounded-xl border border-slate-200 bg-white p-4"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${card.tone}`}><card.icon size={16}/></div><p className="mt-3 text-[10px] font-semibold uppercase tracking-[.06em] text-slate-500">{card.label}</p><p className="mt-1 text-lg font-bold tracking-[-.03em] text-slate-900">{card.value}</p><p className="mt-1 text-[10px] text-slate-400">{card.caption}</p></article>)}</section><aside className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-bold text-blue-900">Saldo pré-pago Meta</p><p className="mt-1 text-xs leading-5 text-blue-800">Crédito disponível na plataforma. Não representa aprovação de verba interna.</p></div><div className="rounded-xl border border-orange-100 bg-orange-50 p-4"><p className="text-xs font-bold text-orange-900">Saldo orçamentário interno</p><p className="mt-1 text-xs leading-5 text-orange-800">Orçamento planejado pelo BI menos o investimento realizado no período.</p></div></aside><section className="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-bold">Ritmo por conta</h2><p className="mt-1 text-xs text-slate-500">Todas as fórmulas utilizam o mesmo período dos filtros</p></div><div className="max-h-[590px] overflow-auto"><table className="w-full min-w-[1830px] text-left text-[11px]"><thead className="sticky top-0 bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{['Conta','Marca','Analista','Período','Orçamento','Valor consumido','Saldo interno','% consumido','Pré-pago Meta','Esperado hoje','Desvio de ritmo','Projeção','Diferença projetada','Dias restantes','Média diária rec.','Status'].map((header)=><th key={header} className="whitespace-nowrap border-b border-slate-200 px-3 py-3">{header}</th>)}</tr></thead><tbody>{rows.map((row)=><BalanceTableRow key={row.id} row={row}/>)}</tbody></table></div></section></>}
  </div></AppShell>;
}

function BalanceTableRow({row}:{row:BalanceRow}) { return <tr className="border-b border-slate-100 hover:bg-orange-50/30"><td className="px-3 py-3 font-semibold text-slate-800">{row.name}</td><td className="px-3 py-3">{row.brand}</td><td className="px-3 py-3">{row.analyst??'Não atribuído'}</td><td className="px-3 py-3">{row.periodLabel}</td><td className="px-3 py-3 font-semibold">{currency(row.budget)}</td><td className="px-3 py-3">{money.format(row.spent)}</td><td className={row.balance!==null&&row.balance<0?'px-3 py-3 font-semibold text-red-600':'px-3 py-3 font-semibold text-emerald-700'}>{currency(row.balance)}</td><td className="px-3 py-3">{row.consumed===null?'N/A':`${(row.consumed*100).toFixed(1).replace('.',',')}%`}</td><td className="px-3 py-3 text-blue-700">{row.prepaid===null?'Não informado':money.format(row.prepaid)}</td><td className="px-3 py-3">{currency(row.expected)}</td><td className={row.paceDeviation!==null&&row.paceDeviation>0?'px-3 py-3 text-red-600':'px-3 py-3 text-amber-700'}>{currency(row.paceDeviation)}</td><td className="px-3 py-3 font-semibold">{currency(row.projection)}</td><td className={row.projectedDifference!==null&&row.projectedDifference<0?'px-3 py-3 text-red-600':'px-3 py-3 text-emerald-700'}>{currency(row.projectedDifference)}</td><td className="px-3 py-3">{row.remainingDays}</td><td className="px-3 py-3">{currency(row.recommendedDaily)}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tone(row.status)}`}>{row.status}</span></td></tr>; }
export function BalancesView(){return <Suspense fallback={<div className="min-h-screen bg-[#f6f7f9]"/>}><BalancesViewInner/></Suspense>;}
