'use client';
import { Suspense, useMemo, useState } from 'react';
import { flexRender, getCoreRowModel, getSortedRowModel, useReactTable, type ColumnDef, type SortingState } from '@tanstack/react-table';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertCircle, ArrowUpDown, Clock3, Download, Info, RefreshCw, Search } from 'lucide-react';
import Link from 'next/link';
import { useSession } from 'next-auth/react';
import { useSearchParams } from 'next/navigation';
import { AppShell } from './app-shell'; import { GlobalFilters } from './global-filters'; import { MetricCard } from './metric-card';
import { integer, money } from '@/lib/demo-data'; import { useAnalyticsData } from '@/lib/use-analytics-data';
import type { PerformanceAccount } from '@/lib/analytics-types';
import { IntegrationAlert, RealDataEmptyState } from './real-data-state';

function exportCsv(rows: PerformanceAccount[]) {
  const headers = ['conta','marca','analista','saldo_alcance','saldo_impressoes','saldo_engajamento','saldo_video','saldo_curtidores','saldo_seguidores','valor_utilizado','orcamento','saldo_orcamentario'];
  const body = rows.map((row) => [row.name,row.brand,row.analyst,balance(row.reach,row.reachGoal)??'',balance(row.impressions,row.impressionsGoal)??'',balance(row.engagement,row.engagementGoal)??'',balance(row.video,row.videoGoal)??'',balance(row.likes,row.likesGoal)??'',balance(row.followers,row.followersGoal)??'',row.spent,row.budget??'',row.budget === null ? '' : row.budget-row.spent].map((value) => `"${String(value??'').replaceAll('"','""')}"`).join(','));
  const url = URL.createObjectURL(new Blob([`\ufeff${headers.join(',')}\n${body.join('\n')}`], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'performance-meta-ads.csv'; anchor.click(); URL.revokeObjectURL(url);
}
function balance(actual: number | null, goal: number | null) { return actual === null || goal === null ? null : actual - goal; }
function SignedValue({ value }: { value: number | null }) { return value === null ? <span className="text-slate-400">N/A</span> : <span className={`font-semibold ${value < 0 ? 'text-red-600' : 'text-emerald-700'}`}>{value > 0 ? '+' : ''}{integer.format(value)}</span>; }

function DashboardViewInner() {
  const { data, loading, error:loadError, reload } = useAnalyticsData(); const {data:session}=useSession(); const params = useSearchParams(); const [query, setQuery] = useState(''); const [sorting, setSorting] = useState<SortingState>([]); const [updating, setUpdating] = useState(false);const[actionError,setActionError]=useState('');
  const rows = useMemo(() => (data?.accounts ?? []).filter((row) => `${row.name} ${row.brand} ${row.analyst}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  const accountHref = (id: string) => { const next = new URLSearchParams(params.toString()); next.set('accountId', id); return `/contas/${id}?${next.toString()}`; };
  const columns = useMemo<ColumnDef<PerformanceAccount>[]>(() => [
    { accessorKey: 'name', header: 'Conta', cell: ({ row }) => <Link href={accountHref(row.original.id)} className="font-semibold text-slate-800 hover:text-orange-700 hover:underline">{row.original.name}</Link> },
    { accessorKey: 'brand', header: 'Marca' }, { accessorKey: 'analyst', header: 'Analista', cell: ({ getValue }) => String(getValue() ?? 'Não atribuído') },
    { id: 'reach', header: 'Alcance', accessorFn: (row) => balance(row.reach, row.reachGoal), cell: ({ getValue }) => <SignedValue value={getValue<number | null>()}/> },
    { id: 'impressions', header: 'Impressões', accessorFn: (row) => balance(row.impressions, row.impressionsGoal), cell: ({ getValue }) => <SignedValue value={getValue<number | null>()}/> },
    { id: 'engagement', header: 'Engajamento', accessorFn: (row) => balance(row.engagement, row.engagementGoal), cell: ({ getValue }) => <SignedValue value={getValue<number | null>()}/> },
    { id: 'video', header: 'Rep. vídeo', accessorFn: (row) => balance(row.video, row.videoGoal), cell: ({ getValue }) => <SignedValue value={getValue<number | null>()}/> },
    { id: 'likes', header: 'Curtidores', accessorFn: (row) => balance(row.likes, row.likesGoal), cell: ({ getValue }) => <SignedValue value={getValue<number | null>()}/> },
    { id: 'followers', header: 'Seguidores', accessorFn: (row) => balance(row.followers, row.followersGoal), cell: ({ getValue }) => <SignedValue value={getValue<number | null>()}/> },
    { accessorKey: 'spent', header: 'Utilizado', cell: ({ getValue }) => money.format(Number(getValue())) },
    { accessorKey: 'budget', header: 'Orçamento', cell: ({ getValue }) => getValue() === null ? 'N/A' : money.format(Number(getValue())) },
    { id: 'budgetBalance', header: 'Saldo', accessorFn: (row) => row.budget === null ? null : row.budget-row.spent, cell: ({ getValue }) => getValue() === null ? <span className="text-slate-400">N/A</span> : <span className={Number(getValue()) < 0 ? 'font-semibold text-red-600' : 'font-semibold text-emerald-700'}>{money.format(Number(getValue()))}</span> },
    { id: 'consumed', header: '% consumido', accessorFn: (row) => row.budget ? row.spent/row.budget : null, cell: ({ getValue }) => getValue() === null ? 'N/A' : `${(Number(getValue())*100).toFixed(1).replace('.',',')}%` },
    { id: 'status', header: 'Status', cell: ({ row }) => { const ratio = row.original.budget ? row.original.spent/row.original.budget : null; const label = ratio === null ? 'Sem orçamento' : ratio > 1.05 ? 'Risco' : ratio < .9 ? 'Abaixo' : 'No ritmo'; const css = ratio === null ? 'bg-slate-100 text-slate-600' : ratio > 1.05 ? 'bg-red-50 text-red-700' : ratio < .9 ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${css}`}>{label}</span>; } },
  // accountHref changes together with the URL and is intentionally captured by this table definition.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  ], [params]);
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({ data: rows, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel() });
  async function update() { setUpdating(true);setActionError(''); try { const response = await fetch('/api/sync/meta', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ start: data?.range.start, end: data?.range.end }) });if(!response.ok){const body=await response.json();throw new Error(body.error??'Falha na atualização.');} reload(); }catch(reason){setActionError(reason instanceof Error?reason.message:'Falha na atualização.');} finally { setUpdating(false); } }
  const updated = data?.updatedAt ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(data.updatedAt)) : 'sem sincronização registrada';
  return <AppShell><div className="mx-auto max-w-[1680px] p-4 md:p-6 lg:p-7">
    <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[.13em] text-orange-700">Performance Meta Ads</p><h1 className="text-2xl font-bold tracking-[-.03em] text-slate-950 md:text-[28px]">Visão consolidada</h1><p className="mt-1 text-sm text-slate-500">Resultados, metas e orçamento das contas em um único lugar.</p></div><div className="flex flex-wrap items-center gap-2"><span className="mr-1 flex items-center gap-1.5 text-xs text-slate-500"><Clock3 size={14}/>Atualizado {updated}</span><button onClick={() => exportCsv(rows)} disabled={!rows.length} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 shadow-sm disabled:opacity-50"><Download size={15}/>Exportar CSV</button>{session?.user.role==='admin'&&<button onClick={update} disabled={updating || loading} className="flex h-9 items-center gap-2 rounded-lg bg-orange-600 px-3.5 text-xs font-semibold text-white shadow-sm disabled:opacity-70"><RefreshCw size={15} className={updating?'animate-spin':''}/>{updating?'Atualizando…':'Atualizar dados'}</button>}</div></div>
    <GlobalFilters accounts={data?.options.accounts} loading={loading}/>
    {(loadError||actionError) && <div role="alert" className="mt-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={17}/>{loadError||actionError}</div>}
    {data && <IntegrationAlert integration={data.integration}/>}
    {loading && <div aria-label="Atualizando indicadores" className="mt-4 grid animate-pulse gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:7},(_,index)=><div key={index} className="h-36 rounded-xl border border-slate-200 bg-white"/>)}</div>}
    {!loading && data && <>{data.empty ? <RealDataEmptyState integration={data.integration}/> : <>
	      <section className="metric-grid mt-4 grid gap-3" aria-label="Indicadores principais">{data.metrics.map(({key,...metric})=><MetricCard key={key} {...metric}/>)}</section>
      <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.65fr)]"><section className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-4"><h2 className="text-sm font-bold">Realizado × meta acumulada</h2><p className="mt-1 text-xs text-slate-500">Investimento acumulado no período filtrado · R$</p></div><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trends}><defs><linearGradient id="areaOrange" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f97316" stopOpacity={.18}/><stop offset="100%" stopColor="#f97316" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef0f3"/><XAxis dataKey="month" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:9}} axisLine={false} tickLine={false}/><Tooltip formatter={(value)=>money.format(Number(value))}/><Legend iconType="circle" iconSize={7}/><Area type="monotone" dataKey="realized" name="Realizado" stroke="#ea580c" strokeWidth={2.5} fill="url(#areaOrange)"/><Area type="monotone" dataKey="goal" name="Meta" stroke="#334155" strokeDasharray="5 5" fill="transparent"/></AreaChart></ResponsiveContainer></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><div className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-bold">Saúde das contas</h2><p className="mt-1 text-xs text-slate-500">Classificação do escopo filtrado</p><div className="mt-2 flex items-center"><div className="h-[138px] w-[48%]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.statusCounts} dataKey="value" innerRadius={39} outerRadius={57} strokeWidth={0}>{data.statusCounts.map((entry)=><Cell key={entry.name} fill={entry.color}/>)}</Pie></PieChart></ResponsiveContainer></div><div className="space-y-3">{data.statusCounts.map((item)=><div key={item.name} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full" style={{background:item.color}}/><span className="min-w-[84px] text-slate-600">{item.name}</span><strong>{item.value}</strong></div>)}</div></div></div><div className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-bold">Investimento × orçamento</h2><p className="mt-1 text-xs text-slate-500">Período filtrado</p><div className="mt-3 h-[120px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.trends}><XAxis dataKey="month" tick={{fontSize:9}} axisLine={false}/><YAxis hide/><Tooltip formatter={(value)=>money.format(Number(value))}/><Bar dataKey="realized" fill="#f97316"/><Bar dataKey="budget" fill="#cbd5e1"/></BarChart></ResponsiveContainer></div></div></section></div>
      <section className="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div><h2 className="text-sm font-bold">Performance por conta</h2><p className="mt-0.5 text-xs text-slate-500">Saldos de atingimento e consumo orçamentário</p></div><label className="flex h-9 w-full items-center gap-2 rounded-lg border border-slate-200 px-3 sm:w-[260px]"><Search size={14} className="text-slate-400"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Pesquisar conta, marca…" className="min-w-0 flex-1 text-xs outline-none"/></label></div><div className="max-h-[440px] overflow-auto"><table className="w-full min-w-[1450px] text-left text-[11px]"><thead className="sticky top-0 z-10 bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{table.getHeaderGroups()[0].headers.map((header)=><th key={header.id} className="whitespace-nowrap border-b border-slate-200 px-3 py-3"><button className="flex items-center gap-1" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header,header.getContext())}<ArrowUpDown size={10}/></button></th>)}</tr></thead><tbody>{table.getRowModel().rows.map((row)=><tr key={row.id} className="border-b border-slate-100 hover:bg-orange-50/40">{row.getVisibleCells().map((cell)=><td key={cell.id} className="whitespace-nowrap px-3 py-3 text-slate-600">{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-[11px] text-slate-500"><span>{rows.length} contas</span><span className="flex items-center gap-1"><Info size={12}/>Alcance consolidado entre contas. Pode existir sobreposição de usuários.</span></div></section>
	    </>}</>}
  </div></AppShell>;
}

export function DashboardView() { return <Suspense fallback={<div className="min-h-screen bg-[#f6f7f9]"/>}><DashboardViewInner/></Suspense>; }
