import { sql } from 'drizzle-orm';
import { boolean, check, date, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';

export const roleEnum = pgEnum('user_role', ['admin','analyst','viewer']);
export const accountStatusEnum = pgEnum('account_status', ['active','paused','archived']);
export const syncStatusEnum = pgEnum('sync_status', ['running','success','failed']);

export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 160 }).notNull(), email: varchar('email', { length: 255 }).notNull(), passwordHash: text('password_hash').notNull(), role: roleEnum('role').notNull().default('viewer'), active: boolean('active').notNull().default(true), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex('users_email_uidx').on(table.email)]);
export const metaConnections = pgTable('meta_connections', {
  id: uuid('id').defaultRandom().primaryKey(), createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'restrict' }).notNull(),
  businessId: varchar('business_id', { length: 100 }), businessName: varchar('business_name', { length: 220 }), encryptedAccessToken: text('encrypted_access_token'),
  tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }), grantedPermissions: jsonb('granted_permissions').$type<string[]>().notNull().default([]),
  status: varchar('status', { length: 40 }).notNull().default('awaiting_authorization'), lastCheckedAt: timestamp('last_checked_at', { withTimezone: true }),
  lastSyncAt: timestamp('last_sync_at', { withTimezone: true }), lastSyncResult: jsonb('last_sync_result'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex('meta_connections_user_uidx').on(table.createdByUserId), uniqueIndex('meta_connections_business_uidx').on(table.businessId).where(sql`${table.businessId} is not null`), index('meta_connections_status_idx').on(table.status)]);
export const metaOauthStates = pgTable('meta_oauth_states', {
  id: uuid('id').defaultRandom().primaryKey(), connectionId: uuid('connection_id').references(() => metaConnections.id, { onDelete: 'cascade' }).notNull(),
  stateHash: varchar('state_hash', { length: 64 }).notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex('meta_oauth_states_hash_uidx').on(table.stateHash), index('meta_oauth_states_connection_idx').on(table.connectionId)]);
export const metaAvailableAccounts = pgTable('meta_available_accounts', {
  id: uuid('id').defaultRandom().primaryKey(), connectionId: uuid('connection_id').references(() => metaConnections.id, { onDelete: 'cascade' }).notNull(),
  metaAccountId: varchar('meta_account_id', { length: 80 }).notNull(), name: varchar('name', { length: 220 }).notNull(), businessId: varchar('business_id', { length: 100 }),
  businessName: varchar('business_name', { length: 220 }), externalStatus: varchar('external_status', { length: 40 }).notNull().default('unknown'),
  currency: varchar('currency', { length: 3 }), timezone: varchar('timezone', { length: 80 }), rawData: jsonb('raw_data').notNull().default({}),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex('meta_available_accounts_scope_uidx').on(table.connectionId, table.metaAccountId), index('meta_available_accounts_meta_idx').on(table.metaAccountId)]);
export const analysts = pgTable('analysts', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 160 }).notNull(), email: varchar('email', { length: 255 }).notNull(), active: boolean('active').notNull().default(true) }, (table) => [uniqueIndex('analysts_email_uidx').on(table.email)]);
export const brands = pgTable('brands', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 160 }).notNull(), code: varchar('code', { length: 40 }).notNull(), active: boolean('active').notNull().default(true) }, (table) => [uniqueIndex('brands_code_uidx').on(table.code)]);
export const adAccounts = pgTable('ad_accounts', { id: uuid('id').defaultRandom().primaryKey(), metaAccountId: varchar('meta_account_id', { length: 80 }).notNull(), name: varchar('name', { length: 220 }).notNull(), brandId: uuid('brand_id').references(() => brands.id).notNull(), market: varchar('market', { length: 100 }).notNull(), analystId: uuid('analyst_id').references(() => analysts.id), facebookPageId: varchar('facebook_page_id', { length: 100 }), instagramProfileId: varchar('instagram_profile_id', { length: 100 }), currency: varchar('currency', { length: 3 }).notNull().default('BRL'), timezone: varchar('timezone', { length: 80 }).notNull().default('America/Sao_Paulo'), status: accountStatusEnum('status').notNull().default('active'), lastSuccessfulSyncAt: timestamp('last_successful_sync_at', { withTimezone: true }) }, (table) => [uniqueIndex('ad_accounts_meta_id_uidx').on(table.metaAccountId), index('ad_accounts_brand_idx').on(table.brandId), index('ad_accounts_analyst_idx').on(table.analystId)]);
export const metaAccountLinks = pgTable('meta_account_links', {
  id: uuid('id').defaultRandom().primaryKey(), connectionId: uuid('connection_id').references(() => metaConnections.id, { onDelete: 'restrict' }).notNull(),
  availableAccountId: uuid('available_account_id').references(() => metaAvailableAccounts.id, { onDelete: 'restrict' }).notNull(), metaAccountId: varchar('meta_account_id', { length: 80 }).notNull(),
  accountId: uuid('account_id').references(() => adAccounts.id, { onDelete: 'restrict' }).notNull(), brandId: uuid('brand_id').references(() => brands.id, { onDelete: 'restrict' }).notNull(),
  market: varchar('market', { length: 100 }).notNull(), analystId: uuid('analyst_id').references(() => analysts.id, { onDelete: 'set null' }), syncEnabled: boolean('sync_enabled').notNull().default(true),
  historyStartDate: date('history_start_date', { mode: 'date' }).notNull(), accessStatus: varchar('access_status', { length: 40 }).notNull().default('not_tested'),
  lastAccessTestAt: timestamp('last_access_test_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex('meta_account_links_meta_uidx').on(table.metaAccountId), uniqueIndex('meta_account_links_internal_uidx').on(table.accountId), uniqueIndex('meta_account_links_available_uidx').on(table.availableAccountId), index('meta_account_links_connection_idx').on(table.connectionId)]);
export const userAccountAccess = pgTable('user_account_access', { userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), accountId: uuid('account_id').references(() => adAccounts.id, { onDelete: 'cascade' }).notNull() }, (table) => [primaryKey({ columns: [table.userId, table.accountId] })]);

export const metaDailyInsights = pgTable('meta_daily_insights', { id: uuid('id').defaultRandom().primaryKey(), insightDate: date('insight_date', { mode: 'date' }).notNull(), accountId: uuid('account_id').references(() => adAccounts.id, { onDelete: 'cascade' }).notNull(), campaignId: varchar('campaign_id', { length: 100 }).notNull().default(''), adsetId: varchar('adset_id', { length: 100 }).notNull().default(''), adId: varchar('ad_id', { length: 100 }).notNull().default(''), spend: numeric('spend', { precision: 18, scale: 2 }).notNull().default('0'), impressions: numeric('impressions', { precision: 20, scale: 0 }).notNull().default('0'), dailyReach: numeric('daily_reach', { precision: 20, scale: 0 }).notNull().default('0'), engagements: numeric('engagements', { precision: 20, scale: 0 }).notNull().default('0'), videoViews: numeric('video_views', { precision: 20, scale: 0 }).notNull().default('0'), clicks: numeric('clicks', { precision: 20, scale: 0 }).notNull().default('0'), results: numeric('results', { precision: 20, scale: 2 }).notNull().default('0'), rawData: jsonb('raw_data').notNull().default({}), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex('meta_insights_identity_uidx').on(table.insightDate, table.accountId, table.campaignId, table.adsetId, table.adId), index('meta_insights_range_idx').on(table.accountId, table.insightDate)]);
export const socialDailyInsights = pgTable('social_daily_insights', { id: uuid('id').defaultRandom().primaryKey(), insightDate: date('insight_date', { mode: 'date' }).notNull(), accountId: uuid('account_id').references(() => adAccounts.id, { onDelete: 'cascade' }).notNull(), profileId: varchar('profile_id', { length: 100 }).notNull(), followersTotal: integer('followers_total').notNull(), likesTotal: integer('likes_total').notNull(), followersDelta: integer('followers_delta').notNull().default(0), likesDelta: integer('likes_delta').notNull().default(0), source: varchar('source', { length: 80 }).notNull() }, (table) => [uniqueIndex('social_insights_identity_uidx').on(table.insightDate, table.profileId), index('social_insights_range_idx').on(table.accountId, table.insightDate)]);

export const metricGoals = pgTable('metric_goals', { id: uuid('id').defaultRandom().primaryKey(), year: integer('year').notNull(), month: integer('month'), accountId: uuid('account_id').references(() => adAccounts.id), brandId: uuid('brand_id').references(() => brands.id), metricKey: varchar('metric_key', { length: 80 }).notNull(), value: numeric('value', { precision: 20, scale: 2 }).notNull(), note: text('note'), source: varchar('source', { length: 80 }).notNull(), changedByUserId: uuid('changed_by_user_id').references(() => users.id, { onDelete: 'set null' }), changedAt: timestamp('changed_at', { withTimezone: true }).defaultNow().notNull() }, (table) => [
  uniqueIndex('metric_goals_scope_uidx').on(table.year, sql`coalesce(${table.month}, 0)`, sql`coalesce(${table.accountId}::text, ${table.brandId}::text)`, table.metricKey),
  index('metric_goals_year_idx').on(table.year),
  check('metric_goals_scope_check', sql`((${table.accountId} is not null)::int + (${table.brandId} is not null)::int) = 1`),
  check('metric_goals_month_check', sql`${table.month} is null or ${table.month} between 1 and 10`),
  check('metric_goals_value_check', sql`${table.value} >= 0`),
]);
export const goalMonthlyWeights = pgTable('goal_monthly_weights', { id: uuid('id').defaultRandom().primaryKey(), year: integer('year').notNull(), accountId: uuid('account_id').references(() => adAccounts.id), brandId: uuid('brand_id').references(() => brands.id), month: integer('month').notNull(), weight: numeric('weight', { precision: 8, scale: 6 }).notNull() }, (table) => [uniqueIndex('goal_weights_scope_uidx').on(table.year, table.accountId, table.brandId, table.month)]);
export const monthlyBudgets = pgTable('monthly_budgets', { id: uuid('id').defaultRandom().primaryKey(), year: integer('year').notNull(), month: integer('month').notNull(), accountId: uuid('account_id').references(() => adAccounts.id, { onDelete: 'cascade' }).notNull(), budget: numeric('budget', { precision: 18, scale: 2 }).notNull(), prepaidBalance: numeric('prepaid_balance', { precision: 18, scale: 2 }), note: text('note'), source: varchar('source', { length: 80 }).notNull(), changedByUserId: uuid('changed_by_user_id').references(() => users.id, { onDelete: 'set null' }), changedAt: timestamp('changed_at', { withTimezone: true }).defaultNow().notNull() }, (table) => [
  uniqueIndex('monthly_budgets_scope_uidx').on(table.year, table.month, table.accountId),
  check('monthly_budgets_month_check', sql`${table.month} between 1 and 12`),
  check('monthly_budgets_value_check', sql`${table.budget} >= 0 and (${table.prepaidBalance} is null or ${table.prepaidBalance} >= 0)`),
]);
export const metricDefinitions = pgTable('metric_definitions', { id: uuid('id').defaultRandom().primaryKey(), key: varchar('key', { length: 80 }).notNull(), displayName: varchar('display_name', { length: 160 }).notNull(), metaField: varchar('meta_field', { length: 160 }).notNull(), unit: varchar('unit', { length: 40 }).notNull(), aggregationRule: varchar('aggregation_rule', { length: 80 }).notNull(), active: boolean('active').notNull().default(true) }, (table) => [uniqueIndex('metric_definitions_key_uidx').on(table.key)]);

export const reachPeriodCache = pgTable('reach_period_cache', { id: uuid('id').defaultRandom().primaryKey(), accountId: uuid('account_id').references(() => adAccounts.id, { onDelete: 'cascade' }).notNull(), level: varchar('level', { length: 30 }).notNull(), startDate: date('start_date', { mode: 'date' }).notNull(), endDate: date('end_date', { mode: 'date' }).notNull(), reach: numeric('reach', { precision: 20, scale: 0 }).notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex('reach_cache_scope_uidx').on(table.accountId, table.level, table.startDate, table.endDate)]);
export const syncRuns = pgTable('sync_runs', { id: uuid('id').defaultRandom().primaryKey(), startedAt: timestamp('started_at', { withTimezone: true }).defaultNow().notNull(), finishedAt: timestamp('finished_at', { withTimezone: true }), connectionId: uuid('connection_id').references(() => metaConnections.id, { onDelete: 'set null' }), accountLinkId: uuid('account_link_id').references(() => metaAccountLinks.id, { onDelete: 'set null' }), accountId: uuid('account_id').references(() => adAccounts.id), periodStart: date('period_start', { mode: 'date' }).notNull(), periodEnd: date('period_end', { mode: 'date' }).notNull(), status: syncStatusEnum('status').notNull().default('running'), recordCount: integer('record_count').notNull().default(0), errorMessage: text('error_message') }, (table) => [index('sync_runs_account_started_idx').on(table.accountId, table.startedAt), index('sync_runs_connection_started_idx').on(table.connectionId, table.startedAt)]);
export const auditLogs = pgTable('audit_logs', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id), action: varchar('action', { length: 120 }).notNull(), entity: varchar('entity', { length: 120 }).notNull(), beforeValues: jsonb('before_values'), afterValues: jsonb('after_values'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (table) => [index('audit_logs_created_idx').on(table.createdAt), index('audit_logs_entity_idx').on(table.entity)]);
